### ISSUE TITLE
Error: Expected instance of PDFDict, but got instance of undefined

### ISSUE THREAD

**Issue by lutfi-haslab** [remdra/sign-pdf-lib#3] opened 2024-03-07 09:37 UTC
Hello, i try to use signVisualAsync but got error.
here my full code:
```javascript
import * as fs from "node:fs";
import * as path from "node:path";
import {
    PdfSigner,
    SignVisualParameters,
    SignerSettings
} from "sign-pdf-lib";

(async () => {
  var pdfPath = path.join(__dirname, "sample.pdf");
  var pdfBuffer = fs.readFileSync(pdfPath);
  var buyerCertificatePath = path.join(__dirname, "lutfiikbalmajid.pfx");
  var buyerCert = fs.readFileSync(buyerCertificatePath);

  var imagePath = path.join(__dirname, "university.jpg");
  var image = fs.readFileSync(imagePath);

  const settings: SignerSettings = {
    signatureLength: 4096,
    rangePlaceHolder: 9999,
    signatureComputer: {
      certificate: buyerCert,
      password: "foo123",
    },
  };

  const parameters: SignVisualParameters = {
    pageNumber: 1,
    rectangle: { 
        left: 50, 
        top: 641, 
        right: 264, 
        bottom: 711
    },

    background: image,
    texts: [{
        lines: [ 
            'JOHN', 
            'DOE'
        ]}, {
        lines: [ 
            'Digitally signed by', 
            'JOHN DOE', 
            'Date: 2023.11.03', 
            '20:28:46 +02\'00\''
        ]}
    ]
};

  const pdfSigner = new PdfSigner(settings);
  const signedPdf = await pdfSigner.signVisualAsync(pdfBuffer, parameters);
  fs.writeFileSync("output777.pdf", Buffer.from(signedPdf));
})();
```
the error:
```bash
/Users/lutfiikbalmajid/hasdev/ejbca-learn/js/node_modules/sign-pdf-lib/node_modules/pdf-lib/cjs/core/errors.js:38
        _this = _super.call(this, msg) || this;
                       ^


Error: Expected instance of PDFDict, but got instance of undefined
```

**Comment by remdra** [comment] 2024-03-07 10:59
I expect this to be a pdf specific error. Please attach the pdf.
I also add the pdf with issues to a regression test suite. Let me know if it is ok to add your pdf there.

**Comment by remdra** [comment] 2024-04-23 15:41
Closing due to missing information.

**Closed as completed by remdra** 2024-04-23 15:41 UTC
